### ISSUE TITLE
Kanban Board - Setup - Module 3 - Group Capstone Project

### ISSUE THREAD

**Issue by ITurres** [ITurres/spacex-travelers-hub#25]
## 🤝 Team Members:

- @ITurres => Missions
- @ahmedeid6842 => Rockets

---

Hi there! I hope all is well.

Here is the link to our Project Kanban: [spaceX-travelers-hub / Kanban](https://github.com/ITurres/spacex-travelers-hub/projects/1)
In this case, we are a group of **`two`** people.

Thank you very much for your review ✨

---

If you require additional information or have any questions, please feel free to contact me on Slack as _**Arturo (Arthur) Emanuel Guerra Iturres**_ or my partner _**Ahmed Eid**_. We'll be happy to assist you. 🎯

---

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive info ✔️
- Tasks distributed equally ✔️  

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ITurres** [comment]
Hi, @gemmen29 George! Thank you for reviewing this issue! Cheers, and happy coding! 🎯

**Comment by ITurres** [comment]
Hi, @gemmen29 George! Thank you for reviewing this issue! Cheers, and happy coding! 🎯
